apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgresql-chart.fullname" . }}
  labels:
    {{- include "postgresql-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "postgresql-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "postgresql-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresqlDatabase }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresqlUsername }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresqlPassword | quote }}
          ports:
            - name: postgresql
              containerPort: 5432
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgresql-data
